# SoftMax Function

See [Wikipedia](https://en.wikipedia.org/wiki/Softmax_function)

In [5]:
import numpy as np

def softmax(x):
    y = np.exp(x)
    sy = np.sum(y)
    if sy > 0:
        y /= sy
    return y

Example 1

In [6]:
x = np.random.randn(10)
print ('Input')
print(x)
y = softmax(x)
print ('Output')
print(y)
print ('Sum of Probabilities')
print(np.sum(y))

Input
[-1.68875668  1.13138837 -0.2295312  -0.07165205 -1.06620531 -0.36520606
  1.60450996  0.67538308 -0.73227855  0.98578282]
Output
[ 0.01143974  0.19195067  0.04922092  0.05763892  0.02131998  0.04297609
  0.30808015  0.12166035  0.02977209  0.16594109]
Sum of Probabilities
1.0


Example 2

In [7]:
x = np.random.randn(3,3)
print ('Input')
print(x)
y = softmax(x)
print ('Output')
print(y)
print ('Sum of Probabilities')
print(np.sum(y))

Input
[[ 2.28805953  0.12368768 -1.26776555]
 [ 1.15383985 -0.45353901 -0.67081265]
 [ 0.6426464   0.07979089  1.44301964]]
Output
[[ 0.4321967   0.04962571  0.01234259]
 [ 0.13902602  0.02786252  0.02242124]
 [ 0.08338494  0.04749442  0.18564587]]
Sum of Probabilities
1.0
