# SoftMax Function

See [Wikipedia](https://en.wikipedia.org/wiki/Softmax_function)

In [1]:
import numpy as np

def softmax(x):
    """ softmax with protection against overflow """
    y = np.exp(np.clip(a=x,a_min=None,a_max=700))
    sy = np.sum(y)
    if sy > 0:
        y /= sy
    return y

Example 1

In [2]:
x = np.random.randn(10)
print ('Input')
print(x)
y = softmax(x)
print ('Output')
print(y)
print ('Sum of Probabilities')
print(np.sum(y))

Input
[-0.38330287  0.0352519  -0.4601353   0.19733624 -0.01689902 -0.36418888
 -1.053575   -0.23397739 -0.15703874  0.81712437]
Output
[ 0.07172116  0.1089992   0.06641702  0.12817864  0.10346047  0.07310522
  0.03669035  0.08327191  0.08993165  0.23822439]
Sum of Probabilities
1.0


Example 2

In [3]:
x = np.random.randn(3,3)
print ('Input')
print(x)
y = softmax(x)
print ('Output')
print(y)
print ('Sum of Probabilities')
print(np.sum(y))

Input
[[ 0.05885673  1.26800194 -0.2960996 ]
 [-0.55166502  0.64390295  1.03041383]
 [-0.02726051 -1.58588675  1.95102733]]
Output
[[ 0.05625461  0.18848778  0.03944596]
 [ 0.03055005  0.10098118  0.14862778]
 [ 0.05161285  0.01086063  0.37317915]]
Sum of Probabilities
1.0
